<?php

$color_schemes=[
    'default' => [
      'title' => t('Default'),
      'colors' => [
      'Primary Color' => '#F93B50',
      'Secondary Color' => '#2d353c',
      ],
    ],
    'set_1' => [
      'title' => t('Color Set 1'),
      'colors' => [
      'Primary Color' => '#7ba021',
      'Secondary Color' => '#3a0a46',
      ],
    ],
    'set_2' => [
      'title' => t('Color Set 2'),
      'colors' => [
      'Primary Color' => '#a24077',
      'Secondary Color' => '#000',
      ],
    ],
    'set_3' => [
      'title' => t('Color Set 3'),
      'colors' => [
      'Primary Color' => '#ffc604',
      'Secondary Color' => '#13152e',
      ],
    ],
    'set_4' => [
      'title' => t('Color Set 4'),
      'colors' => [
      'Primary Color' => '#153156',
      'Secondary Color' => '#000',
      ],
    ],
    'set_5' => [
      'title' => t('Color Set 5'),
      'colors' => [
      'Primary Color' => '#c4832a',
      'Secondary Color' => '#26594c',
      ],
    ],
    'set_6' => [
      'title' => t('Color Set 6'),
      'colors' => [
      'Primary Color' => '#59cad1',
      'Secondary Color' => '#404040',
      ],
    ],
    'set_7' => [
      'title' => t('Color Set 7'),
      'colors' => [
      'Primary Color' => '#711c82',
      'Secondary Color' => '#000',
      ],
    ],
    'set_8' => [
      'title' => t('Color Set 8'),
      'colors' => [
      'Primary Color' => '#000',
      'Secondary Color' => '#1f334e',
      ],
    ],
    'set_9' => [
      'title' => t('Color Set 9'),
      'colors' => [
      'Primary Color' => '#0c5cc9',
      'Secondary Color' => '#404040',
      ],
    ],
];